+ docker inspect -f . python:2-alpine
.
+ python -m py_compile sources/add2vals.py sources/calc.py
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/py_compile.py", line 170, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/py_compile.py", line 162, in main
    compile(filename, doraise=True)
  File "/usr/local/lib/python2.7/py_compile.py", line 106, in compile
    with open(file, 'U') as f:
IOError: [Errno 2] No such file or directory: 'sources/add2vals.py'
script returned exit code 1